services:
  - type: web
    name: internsify-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: VITE_NVIDIA_API_KEY
        sync: false
      - key: VITE_OPENAI_API_KEY
        sync: false
